/* eslint-disable jsx-a11y/no-static-element-interactions */
/* eslint-disable jsx-a11y/click-events-have-key-events */
import { useState } from 'react';
import ContentCard from '../../components/content-card';
import ExpandableTable from '../../components/expandable-table';
import Layout from '../../components/layout';
import style from './auto.module.scss';

const AutoListing = () => {
  const [selectedButton, setSelectedButton] = useState('allTime');

  const handleButtonClick = (button: string) => {
    setSelectedButton(button);
  };

  const rows = [
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
    {
      id: 1,
      columns: [
        { id: 1, value: 'Ado [152760688]', name: 'Mitsubishi Electric HALLE' },
        { id: 2, value: 'Sat 16 Mar 2024 20:00' },
        { id: 3, value: '981' },
        { id: 4, value: '910' },
        { id: 5, value: '0' },
      ],
      details: [
        {
          id: 101,
          columns: [
            { id: 11, value: 'Detail 1.1' },
            { id: 12, value: 'Detail 1.2' },
            { id: 13, value: 'Detail 1.3' },
            { id: 14, value: 'Detail 1.4' },
            { id: 15, value: 'Detail 1.5' },
            { id: 16, value: 'Detail 1.6' },
            { id: 17, value: 'Detail 1.7' },
            { id: 18, value: 'Detail 1.8' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
        {
          id: 102,
          columns: [
            { id: 21, value: 'Detail 1.9' },
            { id: 22, value: 'Detail 1.10' },
            { id: 23, value: 'Detail 1.11' },
            { id: 24, value: 'Detail 1.12' },
            { id: 25, value: 'Detail 1.13' },
            { id: 26, value: 'Detail 1.14' },
            { id: 27, value: 'Detail 1.15' },
            { id: 28, value: 'Detail 1.16' },
          ],
        },
      ],
    },
  ];

  return (
    <Layout pageTitle="Auto Listing">
      <div className={style.mainWrapper}>
        <ContentCard heading="Inventory" className={style.cardClass}>
          <div className={style.btnsDiv}>
            <div
              className={selectedButton === '24hr' ? style.selected : ''}
              onClick={() => handleButtonClick('24hr')}
            >
              24 hr
            </div>
            <div
              className={selectedButton === 'allTime' ? style.selected : ''}
              onClick={() => handleButtonClick('allTime')}
            >
              All Time
            </div>
          </div>
          <ExpandableTable rows={rows} className={undefined} />
        </ContentCard>
      </div>
    </Layout>
  );
};

export default AutoListing;
